import { t } from "elysia";
import { VString, VId } from "bedest-core";

export const VOrganization = t.Object({
  id: VString,
  displayName: VString,
  fullName: VString,
  tagline: t.Nullable(VString),
  email: t.Nullable(VString),
  phone: t.Nullable(VString),
  address: t.Nullable(t.String()),
  workingHours: t.Nullable(VString),
  copyright: t.Nullable(VString),
  domain: t.Nullable(VString),
  country: t.Nullable(VString),
  city: t.Nullable(VString),
  state: t.Nullable(VString),
  zipCode: t.Nullable(VString),
  taxId: t.Nullable(VString),
  currency: t.Nullable(VString),
  timezone: t.Nullable(VString),
  logoId: t.Nullable(VId),
  links: t.Nullable(t.Array(t.String())),
  createdAt: t.Date(),
});

export const VOrganizationUpdate = t.Object({
  displayName: t.Optional(VString),
  fullName: t.Optional(VString),
  tagline: t.Optional(t.Nullable(VString)),
  email: t.Optional(t.Nullable(VString)),
  phone: t.Optional(t.Nullable(VString)),
  address: t.Optional(t.Nullable(t.String())),
  workingHours: t.Optional(t.Nullable(VString)),
  copyright: t.Optional(t.Nullable(VString)),
  domain: t.Optional(t.Nullable(VString)),
  country: t.Optional(t.Nullable(VString)),
  city: t.Optional(t.Nullable(VString)),
  state: t.Optional(t.Nullable(VString)),
  zipCode: t.Optional(t.Nullable(VString)),
  taxId: t.Optional(t.Nullable(VString)),
  currency: t.Optional(t.Nullable(VString)),
  timezone: t.Optional(t.Nullable(VString)),
  logoId: t.Optional(t.Nullable(VId)),
  links: t.Optional(t.Nullable(t.Array(t.String()))),
});
